"""Register the scoped G selection without changing the whole-figure assembly."""
from pathlib import Path
import json, hashlib
ROOT=Path(__file__).resolve().parents[1]
FREEZE=Path('F:/ClassicalConditioning Outputs/ORGER-JOAQUIM/outputs/figure2-assembly/frozen/20261009-G-historical-logmedian')
REVIEW=ROOT/'reviews/figure2_delay_all_versions_20261009.html'
def artifact(p):return dict(path=str(p),sha256=hashlib.sha256(p.read_bytes()).hexdigest())
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
def main():
    freeze=FREEZE/'Fig2_G_Historical_LogMedian.freeze.json'
    assert freeze.exists()
    audit=json.loads((ROOT/'reviews/delay_versions_cleanup_20261009.json').read_text(encoding='utf-8-sig'))
    assert audit['status']=='completed' and artifact(REVIEW)['sha256']==audit['html_sha256']
    selection=dict(figure_id='fig2',panel_id='g',status='frozen',selected_version='Native Historical LogMedian difference, phase-aware LMM',date='2026-10-09',freeze_record=artifact(freeze),svg=artifact(FREEZE/'Fig2_G_Historical_LogMedian.svg'),scientific_selection=artifact(FREEZE/'scientific-selection.json'),all_versions_review=artifact(REVIEW),cleanup=artifact(ROOT/'reviews/delay_versions_cleanup_20261009.json'),assembly_size_mm=[183,98],assembly_scope='G only; full assembly is older and has not been modified or frozen',authorization='freeze the historical log median ... freeze with the stats and the llm',model_limitations='Test3 local M/R unavailable; heavy tails; exploratory; no learning-onset claim')
    write(ROOT/'configs/paper-figures/figure2-G-logmedian-freeze-20261009.json',selection)
    state=FREEZE.parent.parent/'row3-trial-ratio-review/f-recovery-current.json'
    write(state,dict(status='selected-G-frozen; alternatives archived; stale loose files removed',G_selection=str(ROOT/'configs/paper-figures/figure2-G-logmedian-freeze-20261009.json'),selected_freeze=artifact(freeze),consolidated_review=artifact(REVIEW),archive_note='Old directory names are historical only. Download embedded ZIP and use manifest.json for SHA-addressed source contents or canonical selected freeze paths.',original_inputs='F authenticated against402 recorded input hashes; source data not copied or removed',J='inaccessible and untouched'))
    notes=f'''\n\n## Selected G freeze — 2026-10-09\n\nThe author selected native Historical LogMedian with its own D/M/R and\nphase-aware LMM statistics. Scoped current selection:\n`configs/paper-figures/figure2-G-logmedian-freeze-20261009.json`.\nThe immutable freeze is `{freeze.as_posix()}`.\nIt passed the version1.1.1 figure gate with no exceptions. Final standalone\nsize is183×98mm; the whole assembly is older and was not changed.\n\nBlue is control; magenta is Delay. Per-fish values are median(ln positive\nresponse bout frames) minus median(ln positive baseline bout frames), then\nmedian across fish. Windows are[-15,0) and[0,9), CS5–94. Non-bout and empty\nwindows remain missing. Bands are pointwise95% CIs from5,000 whole-fish\nresamples within condition, seed10. Data and fitted results were not changed.\nD Holm8:6; M BH9:5; R raw/BH9:2/2; phase trial BH90 stars19–71.\nTest3 local M/R remains unavailable and is shown n/a; heavy tails and\nonset-inference limitations remain. The primary plot is observed medians,\nwith model tests separately aligned above it, not a fitted curve.\n\nAll alternatives, including mean(log frames), are documented in the single\nself-contained `reviews/figure2_delay_all_versions_20261009.html`. This\nsupersedes the old comparison PDF and loose previews mentioned above.\nIts embedded verified ZIP contains deduplicated alternative data, model\noutputs, code and vector/unique raster sources; selected scientific payload\nresolves to immutable canonical freeze data. Redundant PNG/PDF derivatives\nand PDF QA renders were discarded after consolidation; their hashes and\ndisposition remain in the manifest. Historical audit snapshots retain their\noriginal paths, now resolvable through this manifest.\n\nCleanup removed{audit['removed_file_count']} stale files\n({audit['removed_bytes']:,}bytes).\n`reviews/delay_versions_cleanup_20261009.json` records every original hash,\narchive mapping, discarded derivative and path. Original Digested Data,\nother panel reviews and all historical freezes were preserved; J untouched.\nFour exporter tests and five window-definition tests pass.\n'''
    p=ROOT/'docs/analysis/figures/FIGURE2_DELAY_ALL_VERSIONS_2026-10-09.md'
    if '## Selected G freeze — 2026-10-09' not in p.read_text(encoding='utf-8'):p.write_text(p.read_text(encoding='utf-8')+notes,encoding='utf-8')
    for path,entry in [
        ('Plans/DECISIONS.md','\n\n### 2026-10-09 — G selected Historical LogMedian freeze\nAuthor explicitly selected native bout-only Historical LogMedian with D/M/R and phase-aware LMM trial statistics. See configs/paper-figures/figure2-G-logmedian-freeze-20261009.json. No second log or smoothing. Test3 local M/R n/a; exploratory, no onset claim. All alternatives consolidated in reviews/figure2_delay_all_versions_20261009.html; verified stale Delay copies removed. Whole assembly and D/E freezes unchanged.\n'),
        ('Plans/HANDOFF_BOUT_LOG_VIGOR_PANELS_2026-10-09.md','\n\n### G is now frozen — 2026-10-09\nNative Historical LogMedian is the selected observed outcome, with its fresh phase-aware LMM D/M/R/trial annotations. Scoped record: configs/paper-figures/figure2-G-logmedian-freeze-20261009.json. The alternative mean(log bout frames) remains descriptive only. Consolidated review: reviews/figure2_delay_all_versions_20261009.html. Old loose F review directories are archived/removed; do not select their stale pointers. G is183×98mm standalone; whole-figure assembly remains separately selected.\n')]:
        p=ROOT/path;old=p.read_text(encoding='utf-8')
        if entry.strip() not in old:p.write_text(old+entry,encoding='utf-8')
    print(json.dumps(selection,indent=2))
if __name__=='__main__':main()
