"""One portable chooser for every retained, median-centred F/G/H option."""
from pathlib import Path
import base64,hashlib,html,json
HERE=Path(__file__).resolve().parent; R=HERE.parents[1]/'reviews'
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def uri(p,mime):return 'data:'+mime+';base64,'+base64.b64encode(p.read_bytes()).decode()
def esc(s):return html.escape(str(s))
def load(p):return json.loads(p.read_text())
L=R/'fgh_legacy_layout_20261009'; C=R/'fgh_colour_binning_candidates_20261009'
V7=R/'fgh_version7_unpooled_recipe_20261009'; V8=R/'fgh_version8_percentile_endpoints_20261009'; V9=R/'fgh_version9_discrete_version7_20261009'
options=[
dict(id='v1-c',name='Version 1 C',validation=L/'C_BoutSamples_validation.json',bin='Eligible sample timing',baseline='[−15,0); timepoints carrying complete-bout medians',colour='Continuous; median-centred P10/P90 width scale',defined='269/270',steps='Complete-bout eligible log median, including support outside the display crop → repeat on eligible samples → subtract baseline P50 → divide by (P90−P10)/2 → clip to ±1.',pros='Fine timing; robust bout summary.',cons='Within-bout detail lost; more saturation; complete bouts can cross CS.'),
dict(id='v1-d',name='Version 1 D',validation=L/'D_BoutSamples_validation.json',bin='Eligible sample timing',baseline='[−15,0); same as V1 C',colour='Continuous; larger symmetric denominator',defined='269/270',steps='Same summaries and baseline as V1 C; divide centred values by max(P50−P10,P90−P50), then clip to ±1.',pros='Less or equal saturation than C.',cons='Same bout-summary limitations; weaker contrast.'),
dict(id='v2',name='Version 2 C',validation=L/'C_DirectBins_validation.json',bin='0.5 s direct log means',baseline='[−15,0); finite bin means',colour='Continuous; median-centred P10/P90 width scale',defined='269/270',steps='Mean eligible original log frames in each 0.5 s bin → subtract baseline-bin P50 → divide by (P90−P10)/2 → clip to ±1.',pros='Finer bins; retains direct frame variation.',cons='Scaling hides physical magnitudes; one undefined trial.'),
dict(id='v6-five',name='Version 6 · five colours',validation=C/'Version6_OneSecondCentralBand_validation.json',bin='1 s direct log means',baseline='[−20,0); finite bin means',colour='Five baseline percentile bands; P45–P55 dark centre',defined='270/270',steps='Mean eligible log frames in 1 s bins → subtract baseline P50 → assign bands using baseline P25/P45/P55/P75 → show five managua_r colours. Ties enter the upper band.',pros='Simple categories; all trials defined.',cons='Coarser timing; hides within-band magnitude; up to 20 baseline bins.'),
dict(id='v6-soft',name='Version 6 · softer High',validation=R/'fgh_version6_softer_high_20261009/Version6_SofterHigh_validation.json',bin='Same as V6',baseline='Same as V6',colour='Same five bands; High sampled at managua_r 0.90',defined='270/270',steps='Identical numeric data, bands and layout to Version 6. Only High changes from #ffcf67 to #e09f57; all other colours, including the dark centre, are unchanged.',pros='Less bright High colour.',cons='Smaller visual separation between Above and High.'),
dict(id='v7-physical',name='Version 7 · physical scale (earlier)',validation=V7/'history/physical_bin_centred/Version7_UnpooledRecipe_validation.json',archive=V7/'history/physical_bin_centred',bin='0.5 s bout-summary means',baseline='[−15,0); median of finite bout-summary bins',colour='Continuous physical log differences; ±0.25',defined='270/270',steps='Subtract original eligible log-frame baseline median → take each bout median within [−20,+20) → repeat on eligible frames → mean in 0.5 s bins → subtract median of finite baseline bins. No percentile amplitude scaling. Colour saturation only beyond ±0.25.',pros='Common physical log scale; all trials defined.',cons='Baseline contrast varies across trials and fish.'),
dict(id='v7-scaled',name='Version 7 · scaled (current)',validation=V7/'Version7_UnpooledRecipe_validation.json',bin='0.5 s bout-summary means',baseline='[−15,0); median and P10/P90 of finite bins',colour='Continuous; P10/P90 at ±0.7; limits ±1',defined='257/270',steps='Use V7 physical centred bins → fit separate lower/upper P10/P90 stretches with a symmetric median-preserving centre → apply to all trial bins. At least 10 finite baseline bins required; sparse/degenerate scaled trials undefined. Scaled exports remain unclipped.',pros='Comparable baseline extents; continuous response headroom.',cons='Physical magnitude differs for equal colours; 13 sparse Control trials undefined.'),
dict(id='v8',name='Version 8 · endpoint saturation',validation=V8/'Version8_PercentileEndpoints_validation.json',bin='Same as V7',baseline='Same as V7',colour='Continuous; P10/P90 at ±1; tails saturated',defined='257/270',steps='Divide Version 7 scaled values by 0.7. Keep the same baseline references, centre width and defined-trial mask. P10/P90 reach colour endpoints; values beyond them have saturated colours.',pros='Stronger baseline contrast; full colour range.',cons='Large responses beyond anchors share endpoint colours.'),
dict(id='v9',name='Version 9 · discrete Version 7',validation=V9/'Version9_DiscreteVersion7_validation.json',bin='Same as V7',baseline='[−15,0); Version 7 baseline',colour='Five Version 6 colours on Version 7 values',defined='257/270',steps='Loaded from the verified Version 9 manifest below.',pros='Bout-summary recipe with simple five-colour categories.',cons='Within-band differences hidden; sparse V7 trials remain undefined.')]
v9manifest=load(V9/'data_manifest.json')
options[-1]['steps']=v9manifest['banding_description']
options[-1]['colour']=v9manifest['colour_description']
V10=R/'fgh_version10_three_colours_20261009'
v10manifest=load(V10/'data_manifest.json')
options.append(dict(id='v10',name='Version 10 · three colours',validation=V10/'Version10_ThreeColours_validation.json',
    bin='Same as V7/V9',baseline='[−15,0); Version 7 baseline',colour=v10manifest['colour_description'],defined='257/270',
    steps=v10manifest['banding_description'],pros='Simplest display: lower, near-baseline, higher; dark centre.',
    cons='Merges moderate and extreme deviations; magnitude detail reduced further.'))
protected={}; records=[];cards=[];titles={}
def resolve(path,expected,option):
    p=Path(path)
    if not p.exists() or digest(p)!=expected:
        p=option.get('archive',Path('/no-archive'))/p.name
    assert p.exists() and digest(p)==expected,(path,expected)
    protected[str(p)]=expected
    return p
for o in options:
    val=load(o['validation']); protected[str(o['validation'])]=digest(o['validation'])
    files={Path(row['path']).suffix:resolve(row['path'],row['sha256'],o) for row in val['outputs']}
    for row in val['source_numeric_files']:resolve(row['path'],row['sha256'],o)
    resolve(val['source_data_manifest'],val['source_data_manifest_sha256'],o)
    titles[o['id']]=o['name']; records.append({'id':o['id'],'name':o['name'],'validation':str(o['validation']),'resolved_exports':{k:str(v) for k,v in files.items()}})
    select='<label>Your choice <select data-choice="'+o['id']+'"><option>Undecided</option><option>Keep</option><option>Discard</option></select></label>'
    cards.append('<section id="'+o['id']+'"><div class="heading"><h2>'+esc(o['name'])+'</h2>'+select+'</div><p>'+esc(o['steps'])+'</p><p><b>Baseline:</b> '+esc(o['baseline'])+' · <b>Defined:</b> '+esc(o['defined'])+'</p><p><b>Colours:</b> '+esc(o['colour'])+'</p><p><b>Pros:</b> '+esc(o['pros'])+' <b>Cons:</b> '+esc(o['cons'])+'</p><p><a download="'+files['.pdf'].name+'" href="'+uri(files['.pdf'],'application/pdf')+'">PDF</a> · <a download="'+files['.svg'].name+'" href="'+uri(files['.svg'],'image/svg+xml')+'">SVG</a></p><img alt="'+esc(o['name'])+' F G H heatmaps" src="'+uri(files['.png'],'image/png')+'"></section>')
guide=['# All retained F/G/H versions — 9 October 2026','','V3 has no established recipe in this shortlist. V4/V5 and the original frame-centred V7 are excluded because their displayed baseline median is not guaranteed zero. Four-colour V6 remains discarded.','']
for o in options:guide += ['## '+o['name'],'',o['steps'],'Baseline: '+o['baseline'],'Colour: '+o['colour'],'Defined: '+o['defined'],'Pros: '+o['pros'],'Cons: '+o['cons'],'']
(HERE/'VERSION_GUIDE.md').write_text('\n'.join(guide),encoding='utf-8')
(HERE/'provenance.json').write_text(json.dumps({'options':records,'verified_preserved_files':protected,'no_figure_selection_or_freeze_changes':True},indent=2))
css='''*{box-sizing:border-box}body{font:16px/1.6 system-ui;color:#25313c;background:#f3f5f7;margin:0}main{max-width:1400px;margin:auto;padding:30px 24px}section{background:white;padding:24px;border-radius:8px;margin:24px 0}h1,h2{line-height:1.25}img{display:block;width:100%;height:auto}a{color:#28567b}nav{display:flex;flex-wrap:wrap;gap:12px}.heading{display:flex;justify-content:space-between;gap:15px;align-items:center}select,button{font:15px system-ui;padding:7px;border:1px solid #aaa;border-radius:5px;background:white}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;min-width:1050px;font-size:14px}td,th{text-align:left;vertical-align:top;padding:10px;border-bottom:1px solid #ddd}.notice{background:#faf7ee;padding:14px}.tools{display:flex;flex-wrap:wrap;gap:16px}@media(max-width:700px){main{padding:18px 12px}section{padding:16px}.heading{display:block}}'''
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>All retained F/G/H versions</title><style>'+css+'</style><main><h1>All retained versions: choose a heatmap</h1><p>Ten options, including earlier median-centred V7 with physical colours and the softer High alternative for V6. Every figure and PDF/SVG download is embedded in this single offline file.</p><p class="notice">V3 has no established recipe in this shortlist. V4/V5 and original frame-centred V7 remain excluded because they do not ensure the displayed baseline median is zero. Four-colour V6 remains discarded. V7 physical and V7 scaled are different revisions, clearly identified below.</p><nav><a href="#comparison">Comparison table</a>'+''.join('<a href="#'+o['id']+'">'+esc(o['name'])+'</a>' for o in options)+'</nav>'
page+='<section id="comparison"><h2>Compare all choices</h2><div class="table-wrap"><table><tr><th>Option</th><th>Aggregation / bins</th><th>Baseline</th><th>Colours</th><th>Defined</th><th>Pros</th><th>Cons</th></tr>'+''.join('<tr><td><a href="#'+o['id']+'">'+esc(o['name'])+'</a></td>'+''.join('<td>'+esc(o[k])+'</td>' for k in ['bin','baseline','colour','defined','pros','cons'])+'</tr>' for o in options)+'</table></div></section>'
page+='<section><h2>Shared context</h2><p>F Delay 20221115_07; G 3 s Trace 20230310_08; H Control 20221115_09. Trials 5–94, [−20,+20) s aligned to CS. All candidates use the same reconstructed angular-speed inputs and detected-bout eligibility masks, with natural-log values on eligible frames. Missing cells are black; zero is dark managua_r. Green CS boundaries are at 0 and 10 s; phase boundaries follow trials 14 and 64. Different baseline aggregation populations are explicitly listed per recipe.</p><p>My starting recommendation remains current Version 7 for continuous detail and response headroom. Compare Version 9 if simpler categories read better, and Version 8 if you prefer stronger contrast with endpoint saturation. Choose V7 physical when common physical log magnitudes are the priority. These are review options; no figure has been frozen or selected.</p></section>'
page+=''.join(cards)
page+='<section id="choices"><h2>Your choices</h2><p id="summary"></p><div class="tools"><button id="export">Export choices</button><a download="VERSION_GUIDE.md" href="'+uri(HERE/'VERSION_GUIDE.md','text/markdown')+'">Text guide</a><a download="provenance.json" href="'+uri(HERE/'provenance.json','application/json')+'">Provenance</a></div></section></main>'
js='''const titles=__TITLES__,key='fgh-versions-1-to-6-20261009';let choices={};try{choices=JSON.parse(localStorage.getItem(key)||'{}')}catch(e){}const inputs=[...document.querySelectorAll('[data-choice]')];function summary(){document.getElementById('summary').textContent=['Keep','Discard','Undecided'].map(s=>s+': '+inputs.filter(e=>e.value===s).map(e=>titles[e.dataset.choice]).join(', ')).join(' | ')}inputs.forEach(e=>{e.value=choices[e.dataset.choice]||'Undecided';e.onchange=()=>{choices[e.dataset.choice]=e.value;try{localStorage.setItem(key,JSON.stringify(choices))}catch(e){}summary()}});summary();document.getElementById('export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([inputs.map(e=>titles[e.dataset.choice]+': '+e.value).join('\\n')],{type:'text/plain'}));a.download='FGH_all_version_choices.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};'''.replace('__TITLES__',json.dumps(titles))
page+='<script>'+js+'</script></html>'
(HERE/'index.html').write_text(page,encoding='utf-8')
assert page.count('<img ')==10 and page.count('data-choice="')==10
assert all(digest(Path(p))==h for p,h in protected.items())
print(json.dumps({'options':10,'bytes':len(page.encode()),'preserved_hashes_verified':len(protected)}))
